### ISSUE TITLE
Are we even using `mvn` for the build anymore?

### ISSUE THREAD

**Issue by sarunint** [FabricMC/cfr#17]
In `developer_docs/building.md`, we still point developers to use `mvn` for building, while on GitHub, we use Gradle.

Should we update the documentation to encourage people to use Gradle instead?

**Comment by liach** [comment]
No. We use gradle for our fork and some features of the project (such as newer java version) makes the old maven script obsolete. But updating the documentation may be a bit hard to maintain when the upstream updates it.

**Comment by modmuss50** [comment]
The maven build script should still work just the same as upstream. Gradle is what we use for releasing and consistency with the other fabric projects.
